name: Feature PR
on:
  pull_request:
    branches:
      - "FF-[0-9]*"
      - "!develop"
      - "!main"
    types: [opened, reopened, review_requested, ready_for_review]
  workflow_dispatch:
jobs:
  build:
    if: github.event.pull_request.draft == false
    env:
      DEBUG: ${{ secrets.DEBUG }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install project requirements
        run: |
          pip install -r requirements
      - name: Run pytest
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
